import { StyleSheet } from 'react-native';

import {
  commonBackGroundColor,
  commonBorder,
  commonPadMadStyles,
  commonSizes,
  commonTextStyles,
  commonWidthHeight,
  centerY,
  centerX,
  center,
  commonColor,
  commonJcAlineFlexStyle,
  commonGapStyles,
  commonFlexStyle,
  commonShadowStyles,
  commonAlignSelf,
} from './style.component';

export const styles = (value: any) =>
  StyleSheet.create({
    row: {
      flexDirection: 'row',
      ...commonJcAlineFlexStyle(value),
      ...commonGapStyles(value),
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    column: {
      flexDirection: 'column',
      ...commonJcAlineFlexStyle(value),
      ...commonGapStyles(value),
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },

    container: {
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...commonAlignSelf(value),
      overflow: 'hidden',
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    view: {
      ...commonFlexStyle(value),
      ...commonBackGroundColor(value, true),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    flex_view: {
      ...commonBackGroundColor(value, true),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
      flex: 1,
    },
    text: {
      ...commonTextStyles(value),
    },

    textInput: {
      ...commonTextStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...commonBackGroundColor(value),
    },
    box: {
      ...(value?._flexBasis !== undefined && { flexBasis: value._flexBasis }),
      ...(value?._flexGrow !== undefined && { flexGrow: value._flexGrow }),
      ...(value?._flexShrink !== undefined && {
        flexShrink: value._flexShrink,
      }),
      ...(value?._flexWrap !== undefined && { flexWrap: value._flexWrap }),

      ...commonAlignSelf(value),
      ...commonShadowStyles(value),
      ...commonFlexStyle(value),
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value, true),
      ...commonWidthHeight(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    circle: {
      ...commonWidthHeight(value),
      borderRadius: value?._size,
      borderWidth: value?._bow,
      borderColor: value?._boc,
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      overflow: 'hidden',
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    image: {
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonSizes(value),
      ...commonWidthHeight(value),
      ...commonBorder(value),
    },
    divider: {
      ...(value?._w !== undefined
        ? { width: value?._w ?? 100 }
        : { width: 100 }),
      ...(value?._h !== undefined
        ? { height: value?._h ?? 1.5 }
        : { height: 1.5 }),
      ...(value?._c !== undefined ? { color: value?._c } : {}),
      ...commonColor(value?._c),
      marginVertical: value?._my,
      marginHorizontal: value?._mx,
      borderRadius: value?._bor ?? 0,
      ...(value?._boc !== undefined ? { borderColor: value?._boc } : {}),
    },
    button: {
      ...commonPadMadStyles(value),
      ...commonSizes(value),
      ...commonWidthHeight(value),
      ...commonBorder(value),
      ...commonBackGroundColor(value),
      ...commonAlignSelf(value),
      justifyContent: 'space-around',
      alignItems: 'center',
      flexDirection: 'row',
      overflow: 'hidden',
    },
    rowStyle: {
      flexDirection: 'row',
      justifyContent: value !== undefined ? 'space-around' : 'flex-start',
      alignItems: 'center',
    },
    absolute: {
      position: 'absolute',
      ...commonFlexStyle(value),
      ...(value?._t !== undefined ? { top: value?._t } : {}),
      ...(value?._l !== undefined ? { left: value?._l } : {}),
      ...(value?._r !== undefined ? { right: value?._r } : {}),
      ...(value?._b !== undefined ? { bottom: value?._b } : {}),
      ...(value?._zIndex !== undefined
        ? { zIndex: value?._zIndex }
        : { zIndex: 1 }),
      ...commonPadMadStyles(value),
      ...commonSizes(value, true),
      ...commonWidthHeight(value),
      ...commonBorder(value),
      ...commonBackGroundColor(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
  });
