import { StyleSheet } from 'react-native';

import {
  commonBackGroundColor,
  commonBorder,
  commonPadMadStyles,
  commonSizes,
  commonTextStyles,
  commonWidthHeight,
  centerY,
  centerX,
  center,
  commonColor,
  commonJcAlineFlexStyle,
  commonGapStyles,
  commonFlexStyle,
  commonShadowStyles,
  commonAlignSelf,
  commonBorderColor,
  commonFlexStyles,
} from './style.component';

export const styles = (value: any) =>
  StyleSheet.create({
    row: {
      flexDirection: 'row',
      ...(commonJcAlineFlexStyle(value) as any),
      ...commonGapStyles(value),
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    column: {
      flexDirection: 'column',
      ...(commonJcAlineFlexStyle(value) as any),
      ...commonGapStyles(value),
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },

    container: {
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...commonAlignSelf(value),
      overflow: 'hidden',
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    view: {
      ...commonFlexStyle(value),
      ...commonBackGroundColor(value, true),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    flex_view: {
      ...commonBackGroundColor(value, true),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
      flex: 1,
    },
    text: {
      ...commonTextStyles(value),
    },

    textInput: {
      ...commonTextStyles(value),
      ...commonBorder(value),
      ...commonSizes(value),
      ...commonBackGroundColor(value),
    },
    box: {
      ...commonFlexStyles(value),
      ...commonAlignSelf(value),
      ...commonShadowStyles(value),
      ...commonFlexStyle(value),
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value, true),
      ...commonWidthHeight(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    centredBox: {
      ...commonFlexStyles(value),
      ...commonAlignSelf(value, true),
      ...commonShadowStyles(value),
      ...commonFlexStyle(value),
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonBorder(value),
      ...commonSizes(value, true),
      ...commonWidthHeight(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    circle: {
      ...commonWidthHeight(value),
      borderRadius: value?.$size,
      borderWidth: value?.$bow,
      ...commonBorderColor(value),
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      overflow: 'hidden',
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
    image: {
      ...commonBackGroundColor(value),
      ...commonPadMadStyles(value),
      ...commonSizes(value),
      ...commonWidthHeight(value),
      ...commonBorder(value),
    },
    divider: {
      ...(value?.$w !== undefined
        ? { width: value?.$w ?? 100 }
        : { width: 100 }),
      ...(value?.$h !== undefined
        ? { height: value?.$h ?? 1.5 }
        : { height: 1.5 }),
      ...commonColor(value?.$c),
      marginVertical: value?.$my,
      marginHorizontal: value?.$mx,
      borderRadius: value?.$bor ?? 0,
      ...commonBorderColor(value),
    },
    button: {
      ...commonPadMadStyles(value),
      ...commonSizes(value),
      ...commonWidthHeight(value),
      ...commonBorder(value),
      ...commonBackGroundColor(value),
      ...commonAlignSelf(value),
      justifyContent: 'space-around',
      alignItems: 'center',
      flexDirection: 'row',
      overflow: 'hidden',
    },
    rowStyle: {
      flexDirection: 'row',
      justifyContent: value !== undefined ? 'space-around' : 'flex-start',
      alignItems: 'center',
    },
    absolute: {
      position: 'absolute',
      ...commonFlexStyle(value),
      ...(value?.$t !== undefined ? { top: value?.$t } : {}),
      ...(value?.$l !== undefined ? { left: value?.$l } : {}),
      ...(value?.$r !== undefined ? { right: value?.$r } : {}),
      ...(value?.$b !== undefined ? { bottom: value?.$b } : {}),
      ...(value?.$z !== undefined ? { z: value?.$z } : { zIndex: 1 }),
      ...commonPadMadStyles(value),
      ...commonSizes(value, true),
      ...commonWidthHeight(value),
      ...commonBorder(value),
      ...commonBackGroundColor(value),
      ...centerX(value),
      ...centerY(value),
      ...center(value),
    },
  });
