export type MobilePhone =
  | 'iPhone 14'
  | 'iPhone 14 Plus'
  | 'iPhone 14 Pro'
  | 'iPhone 14 Pro Max'
  | 'iPhone 13'
  | 'iPhone 13 Mini'
  | 'iPhone 13 Pro'
  | 'iPhone 13 Pro Max'
  | 'iPhone 12'
  | 'iPhone 12 Mini'
  | 'iPhone 12 Pro'
  | 'iPhone 12 Pro Max'
  | 'iPhone SE (3rd generation)'
  | 'iPhone SE (2nd generation)'
  | 'iPhone 11'
  | 'iPhone 11 Pro'
  | 'iPhone 11 Pro Max'
  | 'iPhone XR'
  | 'iPhone XS'
  | 'iPhone XS Max'
  | 'iPhone X'
  | 'iPhone 8'
  | 'iPhone 8 Plus'
  | 'Samsung Galaxy S23'
  | 'Samsung Galaxy S23 Ultra'
  | 'Samsung Galaxy Z Fold 5'
  | 'Samsung Galaxy Z Flip 5'
  | 'Samsung Galaxy A54'
  | 'Google Pixel 7'
  | 'Google Pixel 7 Pro'
  | 'Google Pixel 6a'
  | 'OnePlus 11'
  | 'OnePlus Nord 2T'
  | 'Xiaomi 13'
  | 'Xiaomi 13 Pro'
  | 'Huawei P60 Pro'
  | 'Huawei Mate 50'
  | 'Sony Xperia 1 IV'
  | 'Sony Xperia 5 IV'
  | 'Asus ROG Phone 6'
  | 'Asus Zenfone 9'
  | 'Motorola Edge 40'
  | 'Motorola Razr 2023'
  | 'Oppo Find X6 Pro'
  | 'Oppo Reno 8 Pro'
  | 'Vivo X80 Pro'
  | 'Realme GT2 Pro'
  | 'Nokia G60'
  | 'Redmi Note 12 Pro';
